version: '3.5'
services:
  minecraft-server:
     image: kaekh/minecraft-forge
     restart: "on-failure:5"
     ports:
        - "25565:25565/tcp"
     volumes:
        - ./server:/minecraft/server
     environment:
        MINMEN: 4G
        MAXMEN: 8G
        FORGEVERSION: 1.18.2-40.1.54
